import React, { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { CalculationInputs, CalculationResults } from './types';
import InputSummary from './results/InputSummary';
import FeeBreakdown from './results/FeeBreakdown';
import TaxCalculation from './results/TaxCalculation';
import FinalResult from './results/FinalResult';
import html2canvas from 'html2canvas';
import html2pdf from 'html2pdf.js';
import { useLanguage } from '@/contexts/LanguageContext';
import { useIsMobile } from '@/hooks/use-mobile';

interface ResultsDisplayProps {
  results: CalculationResults | null;
  inputs: CalculationInputs;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ results, inputs }) => {
  const resultsRef = useRef<HTMLDivElement>(null);
  const { t, language } = useLanguage();
  const isMobile = useIsMobile();

  const hasValidResults = results &&
    (inputs.quantity &&
      ((inputs.transactionType === 'buy' && inputs.buyPrice) ||
        (inputs.transactionType === 'sell' && inputs.buyPrice && inputs.sellPrice)));

  const formattedDate = () => {
    const today = new Date();
    return today.toLocaleDateString(language === 'ne' ? 'ne-NP' : 'en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const createClonedContentWithHeaderFooter = () => {
    if (!resultsRef.current) return null;

    const element = resultsRef.current;
    const date = formattedDate();
    const clone = element.cloneNode(true) as HTMLElement;

    // Add header
    const header = document.createElement('div');
    header.style.textAlign = 'center';
    header.style.marginBottom = '20px';
    header.innerHTML = `
      <div style="font-size: 40px; font-weight: bold;">
        Reports by ShareCalculator.App
      </div>
    `;
    clone.insertBefore(header, clone.firstChild);

    // Add footer
    const footer = document.createElement('div');
    footer.style.textAlign = 'center';
    footer.style.fontSize = '32px';
    footer.style.color = '#888';
    footer.style.marginTop = '40px';
    footer.innerHTML = `
      Generated by sharecalculator.app on ${date}<br/>
      For more visit <a href="https://sharecalculator.app" target="_blank">ShareCalculator.App</a>
    `;
    clone.appendChild(footer);

    return clone;
  };

  const handleDownloadPDF = () => {
    const content = createClonedContentWithHeaderFooter();
    if (!content) return;

    const opt = {
      margin: [10, 10],
      filename: 'nepse-calculation-result.pdf',
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    };

    html2pdf().set(opt).from(content).save();
  };

  const handleDownloadPNG = async () => {
    const content = createClonedContentWithHeaderFooter();
    if (!content) return;

    // Temporarily attach to DOM to allow layout rendering
    document.body.appendChild(content);
    content.style.position = 'absolute';
    content.style.left = '-9999px';

    try {
      const canvas = await html2canvas(content, {
        scale: 2,
        useCORS: true,
        logging: false,
      });

      canvas.toBlob((blob) => {
        if (blob) {
          const link = document.createElement('a');
          link.href = URL.createObjectURL(blob);
          link.download = 'nepse-calculation-result.png';
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
        }
      }, 'image/png');
    } catch (error) {
      console.error('Error generating PNG:', error);
    } finally {
      document.body.removeChild(content);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <h2 className="text-base sm:text-lg font-medium mb-2 sm:mb-4">{t('calculator.results')}</h2>

      <div
        ref={resultsRef}
        className="bg-white p-3 sm:p-4 rounded-lg flex-grow"
        style={{ minHeight: isMobile ? '300px' : '400px' }}
      >
        <InputSummary inputs={inputs} />
        <FeeBreakdown results={results} />
        {inputs.transactionType === 'sell' && <TaxCalculation results={results} inputs={inputs} />}
        <FinalResult results={results} inputs={inputs} />
      </div>

      <div className="mt-3 sm:mt-4 flex flex-wrap gap-2 justify-end min-h-[32px] sm:min-h-[38px]">
        {hasValidResults && (
          <>
            <Button
              onClick={handleDownloadPDF}
              size={isMobile ? 'sm' : 'default'}
              className="text-xs sm:text-sm h-8 sm:h-10"
            >
              {t('download.pdf')}
            </Button>

            <Button
              onClick={handleDownloadPNG}
              size={isMobile ? 'sm' : 'default'}
              variant="outline"
              className="text-xs sm:text-sm h-8 sm:h-10"
            >
              {t('download.png')}
            </Button>
          </>
        )}
      </div>
    </div>
  );
};

export default ResultsDisplay;
